"""add product_imports credit_cost

Revision ID: 53d441e69de6
Revises: baa7b2ede411
Create Date: 2026-08-19 17:33:24.334372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d441e69de6'
down_revision: Union[str, Sequence[str], None] = 'baa7b2ede411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_imports', sa.Column('credit_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_imports', 'credit_cost')
    # ### end Alembic commands ###
