"""add name category preview_asset_url to templates

Revision ID: 7e11343179fd
Revises: 4e95a697f741
Create Date: 2026-08-26 14:02:19.603680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e11343179fd'
down_revision: Union[str, Sequence[str], None] = '4e95a697f741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('name', sa.String(), nullable=False))
    op.add_column('templates', sa.Column('category', sa.String(), nullable=False))
    op.add_column('templates', sa.Column('preview_asset_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'preview_asset_url')
    op.drop_column('templates', 'category')
    op.drop_column('templates', 'name')
    # ### end Alembic commands ###
