"""add brand kits marks and assets is_saved_product

Revision ID: a4f9c148aabb
Revises: 8c59f976c159
Create Date: 2026-08-26 14:11:29.035421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f9c148aabb'
down_revision: Union[str, Sequence[str], None] = '8c59f976c159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_kits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('palette', sa.JSON(), nullable=False),
    sa.Column('heading_font', sa.String(), nullable=True),
    sa.Column('body_font', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('brand_marks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_kit_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('variant', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['brand_kit_id'], ['brand_kits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assets', sa.Column('is_saved_product', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'is_saved_product')
    op.drop_table('brand_marks')
    op.drop_table('brand_kits')
    # ### end Alembic commands ###
