"""add asset source_asset_id for exports

Revision ID: d38aaad06785
Revises: a4f9c148aabb
Create Date: 2026-08-26 14:19:11.241627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38aaad06785'
down_revision: Union[str, Sequence[str], None] = 'a4f9c148aabb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('source_asset_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'assets', 'assets', ['source_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'source_asset_id')
    # ### end Alembic commands ###
