"""add tools table

Revision ID: d3e31e5bef95
Revises: e3d3552b463c
Create Date: 2026-08-19 16:42:45.046350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e31e5bef95'
down_revision: Union[str, Sequence[str], None] = 'e3d3552b463c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('feature_type', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('output_media_type', sa.String(), nullable=False),
    sa.Column('default_model_id', sa.String(), nullable=True),
    sa.Column('credit_cost', sa.Integer(), nullable=False),
    sa.Column('pricing_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('feature_type')
    )
    op.add_column('generation_jobs', sa.Column('external_job_id', sa.String(), nullable=True))
    op.add_column('generation_jobs', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_jobs', 'provider')
    op.drop_column('generation_jobs', 'external_job_id')
    op.drop_table('tools')
    # ### end Alembic commands ###
